apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: balaji-project
        image: balajikendey/myfirstproject:3